"""empty message

Revision ID: 23edf59836b0
Revises: 2e9cea341fe4
Create Date: 2021-06-12 01:36:29.019579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23edf59836b0'
down_revision = '2e9cea341fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('question', sa.Integer(), nullable=False),
    sa.Column('isCorrect', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    # ### end Alembic commands ###
